### ISSUE TITLE
Switching over to manually-programmed galleries

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-start-here#2]
@rubillionaire - snippets from the group's Wed Nov 11 edu slack conversation:

Huy  2:35 PM
Can folks check starthere.risd.edu?
2:35
Getting broken galleries, but not sure if it’s just me.
<img width="1589" alt="Screen Shot 2020-11-11 at 2 34 41 PM" src="https://user-images.githubusercontent.com/14020234/99113492-57fa4c00-25bd-11eb-9c26-4f5527d2043e.png">

Rubén Rodríguez  2:45 PM
looking at the links, such as https://www.instagram.com/p/Bk3pQSog3ZR/media/?size=l it looks like facebook has changed how instagram embeds work

Jay Marol  2:48 PM
not working for me in chrome too

Rubén Rodríguez  2:54 PM
yeah the individual posts use a different method to be displayed, they include the instagram profile including the number of likes and such. we would have to migrate all of the gallery posts to use this same method of being displayed. although we avoided that to begin with because it was very slow to load, there is a bunch more work the browser has to do to render the full profile view vs just the image

Huy  3:07 PM
I wonder if we can at least start pulling the images for the time being and move towards faking it? So not actively pulling images from instagram, but hosting on our end with a link out to the post.
3:08
What do you think @Brian Clark?

Jay Marol  3:28 PM
@Rubén Rodríguez in the meantime should we backup the data and remove the gallery questions?

Rubén Rodríguez  3:31 PM
@Jay Marol that would make sense for now. i just created another snapshot of the site in addition to the one that is captured every morning

Brian Clark  3:43 PM
@Rob Albanese @Jay Marol are we affected by this? https://wersm.com/facebook-and-instagram-dropping-embedded-content-support-on-wordpress-sites/. “API update will remove support for unauthenticated Facebook and Instagram embeds”

Rubén Rodríguez  4:58 PM
@Brian Clark the article describes why our images were no longer loading. it looks like we can still manually copy embed codes and place them in our CMS, but doing it programmatically now requires a facebook account to authenticate with. i suggest we stick to our manual embeds like we have them, and in the case of the galleries, i like huy’s idea of hosting the images on our end, and linking out to them. a bunch of galleries full of embeds is a tall order for most browsers, so hosting and linking out would be a good way to keep our previous functionality

Brian Clark  5:01 PM
@Rubén Rodríguez agree, what’s the dev level of effort on switching over to manually-programmed galleries

Rubén Rodríguez  1 day ago
probably ~ a day. a few hours to get things coded and tested, a few more for sharing and refining

Brian Clark  1 day ago
ok, let’s slot this after the other news & commguide stuff.

**Comment by rubillionaire** [comment]
@cmiller02 there is now a `Galleries` content type that holds images that are uploaded from Instagram into the CMS. alongside each image is a link text and link url field.

the restored galleries powered by this new content type are up for review on https://start-here.risd.systems

let me know how that looks!

**Comment by cmiller02** [comment]
Wow, thanks @rubillionaire ! Admittedly I've never worked in this site, so I think it would be best for @mmarol and Lauren to test out what you've done. @mmarol would you mind? And in the meantime (since Lauren isn't in Github) I'll provide her with Ruben's above comment.

**Comment by cmiller02** [comment]
This got the thumbs up from @mmarol and Lauren, so I'm sliding this into our Ready to deploy column!

**Comment by rubillionaire** [comment]
@cmiller02 thanks for confirming! this is now live at https://starthere.risd.edu/

**Comment by rubillionaire** [comment]
the galleries that come after the answer to questions 9, 15 & 18 have been restored on https://start-here.risd.systems

they are populated in the `Galleries` content type, and then pulled into the question using the `Related Gallery` widget in the `Questions` repeatable of the `List of Questions` content type.

@cmiller02 let me know how this whole set up looks to you. when its ready we can cut it live on starthere.risd.edu

**Comment by rubillionaire** [comment]
@cmiller02 has confirmed with lauren that the setup will work going forward.

i have deployed to starthere.risd.edu

**Comment by cmiller02** [comment]
All looks great @rubillionaire ! Looked in the CMS as well and all is exactly how we'd talked about. Thank you! I think we can close if you're good to.

**Comment by rubillionaire** [comment]
thanks for confirming, @cmiller02 ! the issue is closed and i moved it to the deployed column of the project board.
